### ISSUE TITLE
Does this support windows 10?

### ISSUE THREAD

**Issue by 94maldini** [helson-lin/oimi-live#1]
because I get an error in this section
```
> oimi-live@1.0.2 dev
> nodemon ./bin/index.js

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node ./bin/index.js`
fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (C:\node\oimi-live-main\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\node\oimi-live-main\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\node\oimi-live-main\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by helson-lin** [comment]
Of course， it’s support. This error mean you node version is higher. You can try to change your node version to 16 below

---- Replied Message ----
| From | Maldini ***@***.***> |
| Date | 03/17/2024 22:49 |
| To | helson-lin/oimi-live ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [helson-lin/oimi-live] Does this support windows 10? (Issue #1) |

because I get an error in this section

> ***@***.*** dev
> nodemon ./bin/index.js

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node ./bin/index.js`
fs.js:47
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:47:5
    at req_ (C:\node\oimi-live-main\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\node\oimi-live-main\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\node\oimi-live-main\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
[nodemon] app crashed - waiting for file changes before starting...
